Containerize for static nginx k8s deployent
freedomofpress/dangerzone.rocks pull request #23
Opened 2023-07-11 19:32 UTC by maeve-fpf

We'd like to deploy this site to FPF's own infrastructure, so add a small nginx container that can be used to serve the files.

In the future, merges to this repo will be picked up by the same infrastructure as other FPF web sites/static docs sites.

A followup should be made after DNS is pointed to GKE to remove the `CNAME` file for Github Pages, as it will no longer be needed.

2023-07-11 23:02 UTC, maeve-fpf commented
To test locally, do

```
docker build -f deploy/Dockerfile .
```

and then

```
docker run --rm -p 127.0.0.1:5080:5080 TAG
```

where `TAG` is what was built.

2023-07-12 16:18 UTC, eloquence commented on deploy/nginx.conf
> +            rewrite ^/_/downloads/en/latest/pdf/$ /en/latest/SecureDropSupport.pdf permanent;
Holdover from docs config

2023-07-12 16:29 UTC, eloquence requested changes
Does what it says on the tin :). One bit left from docs config.

2023-07-12 20:19 UTC, maeve-fpf commented
Ah! I realized why that happened - I had made some changes and didn't `git add`. Should be correct now.

2023-07-12 22:10 UTC, eloquence approved these changes
LGTM!

2023-07-12 22:10 UTC, merged