Update "How it works" section and add some articles about Dangerzone
freedomofpress/dangerzone.rocks pull request #39
Opened 2024-05-14 15:16 UTC by apyrgio

Update the "How it works" section, since it was out of sync with the recent developments on Dangerzone. Also, add the results of our latest security audit, as well as some articles from journalism-related media, which mention the use of Dangerzone.

See also freedomofpress/dangerzone#807

2024-08-19 14:22 UTC, apyrgio commented
Heads up, I've converted the changes in this PR from HTML to Markdown, to make them work for 11ty.

2024-08-19 19:51 UTC, eloquence commented on src/about.md
> +While we are doing our best to inform journalists about these risks and keep them as safe as possible, we believe its important for third-parties to independently assess our assumptions. For this rea
its important->it's important

third-parties->third parties

except for 3 low-risk and 7 informational findings. -> (it identified 3 low-risk and 7 informational findings) 

(The "except for" is not in fact an exception to the previous statement.)

2024-08-19 19:53 UTC, eloquence commented on src/about.md
> +* [When security matters: working with Qubes OS at the Guardian](https://www.theguardian.com/info/2024/apr/04/when-security-matters-working-with-qubes-os-at-the-guardian)
I'd add dates/authors for these, so the list can be ordered reverse chron as it gets longer.

2024-08-19 20:12 UTC, eloquence requested changes
A couple of nits but mostly LGTM! Should we wait with merging this until https://github.com/freedomofpress/dangerzone/pull/748 lands? AIUI this describes the post-748 architecture.

2024-08-20 05:59 UTC, apyrgio commented on src/about.md
> +While we are doing our best to inform journalists about these risks and keep them as safe as possible, we believe its important for third-parties to independently assess our assumptions. For this rea
Thanks for the fixes Erik. I've changed this paragraph in 57257c51b45ee876cbaa08fca3677bda84b4236e.

2024-08-20 06:01 UTC, apyrgio commented on src/about.md
> +* [When security matters: working with Qubes OS at the Guardian](https://www.theguardian.com/info/2024/apr/04/when-security-matters-working-with-qubes-os-at-the-guardian)
Makes sense to me. I've taken a stab at c5bbd4aaca0650695865767204b08159bab3ecea using italics for the extra data (else it looked a bit off to me...). Tell me if you have a better idea!

2024-08-20 06:04 UTC, apyrgio commented
> Should we wait with merging this until https://github.com/freedomofpress/dangerzone/pull/748 lands? AIUI this describes the post-748 architecture.

Actually, with this PR we describe the architecture we have currently (minus the gVisor parts which will be covered in #41). We still refer to the second container in the section of how Dangerzone works, and the fact that we mount the pixel data in it. Once we merge freedomofpress/dangerzone#748, we'll have to update it once more.

2024-08-20 15:54 UTC, eloquence approved these changes
LGTM!

2024-08-20 17:44 UTC, merged